const images = {
  badminton_set: "../assets/product-images/badminton-set.jpg",
  bag_of_ice: "../assets/product-images/bag_of.jpg",
  basket: "../assets/product-images/basket.jpg",
  bbq_sauce: "../assets/product-images/bbq-sauce.jpg",
  birthday_banner: "../assets/product-images/birthday-banner.jpg",
  birthday_cake: "../assets/product-images/birthday-cake.jpg",
  blanket: "../assets/product-images/blanket.jpg",
  champagne: "../assets/product-images/champagne.jpg",
  charcuterie: "../assets/product-images/charcuterie.jpg",
  chips: "../assets/product-images/chips.jpg",
  collapsable_water_dish: "../assets/product-images/collapsable-water-dish.jpg",
  cooler: "../assets/product-images/cooler.jpg",
  frisbee: "../assets/product-images/frisbee.jpg",
  fruit_plate: "../assets/product-images/fruit-plate.jpg",
  grill_lovers: "../assets/product-images/grill-lovers.jpg",
  ham_sandwich: "../assets/product-images/ham-sandwich.jpg",
  hamburger_buns: "../assets/product-images/hamburger-buns.jpg",
  hamburger_patties: "../assets/product-images/hamburger-patties.jpg",
  hotdog_buns: "../assets/product-images/hotdog-buns.jpg",
  hotdogs: "../assets/product-images/hotdogs.jpg",
  ketchup: "../assets/product-images/ketchup.jpg",
  mustard: "../assets/product-images/mustard.jpg",
  pack_of_beer: "../assets/product-images/pack-of-beer.jpg",
  pack_of_coolers: "../assets/product-images/pack-of-coolers.jpg",
  paper_plates: "../assets/product-images/paper-plates.jpg",
  relish: "../assets/product-images/relish.jpg",
  reusable_water_bottle: "../assets/product-images/reusable-water-bottle.jpg",
  roast_beef_sandwich: "../assets/product-images/roast-beef-sandwich.jpg",
  romantic_basket: "../assets/product-images/romantic-basket.jpg",
  salad: "../assets/product-images/salad.jpg",
  salty_snacks: "../assets/product-images/salty-snacks.jpg",
  soda_pop: "../assets/product-images/sode-pop.jpg",
  sunscreen: "../assets/product-images/sunscreen.jpg",
  sweet_dessert: "../assets/product-images/sweet-dessert.jpg",
  tennis_balls: "../assets/product-images/tennis-balls.jpg",
  tongs: "../assets/product-images/tongs.jpg",
  turkey_sandwich: "../assets/product-images/turkey-sandwich.jpg",
  umbrella: "../assets/product-images/umbrella.jpg",
  veggie_sandwich: "../assets/product-images/veggie-sandwich.jpg",
  water_bottles: "../assets/product-images/water-bottles.jpg",
  wine: "../assets/product-images/wine.jpg",
};

export default images;
