INSERT INTO products (name, price_cents, description, is_basket, portions, is_deluxe, image) VALUES
('Wine', 2000, 'A fine bottle of wine', false, 1, false, 'wine.png'),
('Champagne', 5000, 'A bottle of high-quality champagne', false, 1, false, 'champagne.png'),
('Charcuterie Board', 1500, 'Assorted meats and cheeses', false, 1, false, 'charcuterie_board.png'),
('Fruit Plate', 1200, 'Seasonal fresh fruit', false, 1, false, 'fruit_plate.png'),
('Turkey Sandwich', 700, 'Tasty fresh turkey sandwich', false, 1, false, 'assorted_sandwiches.png'),
('Ham Sandwich', 700, 'Tasty fresh ham sandwich', false, 1, false, 'assorted_sandwiches.png'),
('Roast Beef Sandwich', 700, 'Tasty fresh roast beef sandwich', false, 1, false, 'assorted_sandwiches.png'),
('Veggie Sandwich', 700, 'Tasty fresh roast beef sandwich', false, 1, false, 'assorted_sandwiches.png'),
('Salty Snacks', 500, 'Assorted salty snacks', false, 1, false, 'salty_snacks.png'),
('Sweet Dessert', 1500, 'Decadent sweet treats', false, 1, false, 'sweet_dessert.png'),
('Soda Pop', 200, 'A variety of soda flavors', false, 1, false, 'soda_pop.png'),
('Chips', 300, 'Bag of potato chips', false, 1, false, 'chips.png'),
('Frisbee', 1000, 'Durable frisbee for outdoor fun', false, 1, false, 'frisbee.png'),
('Veggie Platter', 1000, 'Fresh cut vegetables with dip', false, 1, false, 'veggie_platter.png'),
('Water Bottles', 500, 'Pack of bottled water', false, 1, false, 'water_bottles.png'),
('Salad', 800, 'Fresh mixed greens salad', false, 1, false, 'salad.png'),
('Branded Quik-A-Nik Blanket', 2500, 'Picnic blanket with branding', false, 1, false, 'branded_quik-a-nik_basket.png'),
('Branded Quik-A-Nik Cooler', 3000, 'Insulated cooler with branding', false, 1, false, 'branded_quik-a-nik_cooler.png'),
('Paper Plates', 200, 'Pack of disposable paper plates', false, 1, false, 'paper_plates.png'),
('Birthday Cake', 3500, 'Delicious birthday cake', false, 1, false, 'birthday_cake.png'),
('Birthday Banner', 500, 'Festive birthday banner', false, 1, false, 'birthday_banner.png'),
('6 Pack Of Beer', 1200, 'Pack of 6 beer cans', false, 1, false, '6_pack_of_beer.png'),
('6 Pack Of Coolers', 1200, 'Pack of 6 alcohol coolers', false, 1, false, '6_pack_of_coolers.png'),
('Bag Of Ice', 300, 'Large bag of ice', false, 1, false, 'bag_of_ice.png'),
('Frozen Hamburger Patties', 800, 'Pack of frozen hamburger patties', false, 1, false, 'frozen_hamburger_patties.png'),
('Hot Dogs', 700, 'Pack of hot dogs', false, 1, false, 'hot_dogs.png'),
('Hamburger Buns', 200, 'Pack of hamburger buns', false, 1, false, 'hamburger_buns.png'),
('Hot Dog Buns', 200, 'Pack of hot dog buns', false, 1, false, 'hot_dog_buns.png'),
('Tongs', 500, 'Stainless steel tongs', false, 1, false, 'tongs.png'),
('Sunscreen', 800, 'Bottle of SPF 30 sunscreen', false, 1, false, 'sunscreen.png'),
('Badminton Set', 2000, 'Complete badminton set for outdoor fun', false, 1, false, 'badminton_set.png'),
('BBQ Sauce', 300, 'Bottle of BBQ sauce', false, 1, false, 'bbq_sauce.png'),
('Ketchup', 200, 'Bottle of ketchup', false, 1, false, 'ketchup.png'),
('Mustard', 200, 'Bottle of mustard', false, 1, false, 'mustard.png'),
('Relish', 200, 'Jar of relish', false, 1, false, 'relish.png'),
('Umbrella', 3000, 'Large, sturdy umbrella', false, 1, false, 'umbrella.png'),
('Reusable Water Bottle', 1000, 'Eco-friendly reusable water bottle', false, 1, false, 'reusable_water_bottle.png'),
('Tennis Balls', 800, 'Can of 3 tennis balls', false, 1, false, 'tennis_balls.png'),
('Collapsable Water Dish', 500, 'Portable water dish for pets', false, 1, false, 'collapsable_water_dish.png'),
('Romatic Basket', 7500, '1 Bottle of Champagne, 1 Charcuterie Board, 1 Fruit Platter', true, 2, false, 'romantic_basket.png'),
('Family Basket A', 6000, '2 Turkey Sandwiches, 1 Ham Sandwich, 1 Veggie Sandwich, 1 Bag of Chips, 1 Bag of Brownies, 4 Cans of Pop', true, 4, false, 'family_basket.png'),
('Family Basket B', 6000, '2 Ham Sandwiches, 1 Roast Beef Sandwich, 1 Veggie Sandwich, 1 Bag of Pretzels, 1 Bag of Candies, 2 Cans of Pop, 2 Bottles of Water', true, 4, false, 'family_basket.png'),
('Family Basket C', 6000, '2 Veggie Sandwiches, 2 Turkey Sandwiches, 1 Veggie Platter, 1 Fruit Platter, 1 Assorted Trail Mix, 4 Bottles of Water', true, 4, false, 'family_basket.png'),
('Family Basket D', 6000, '2 Roast Beef Sandwiches, 2 Ham Sandwiches, 1 Bag of Chips, 1 Bag of Brownies, 4 Cans of Pop', true, 4, false, 'family_basket.png'),
('Kids Fun Basket', 3000, '1 Bag of Chips, 2 Cans of Pop, 1 Frisbee', true, 2, false, 'kids_basket.png'),
('Healthy Quik-A-Nik', 4000, '1 Fruit Platter, 1 Veggie Platter, 4 Water Bottles, 1 Large Garden Salad', true, 4, false, 'healthy_basket.png'),
('Deluxe Quik-A-Nik Starter Kit', 10000, '1 Branded Quik-A-Nik Blanket, 1 Branded Quik-A-Nik Cooler, Family Basket A', true, 4, true, 'deluxe_basket.png'),
('Celebration Extravaganza', 10000, '15 Assorted Sandwiches, 1 Birthday Cake, 1 Birthday Banner, 1 Package of Paper Plates', true, 15, true, 'cele_basket.png'),
('Adult Hydration Basket', 4000, '6 Pack of Beer, 6 Pack of Wine Coolers, 1 Bag of Ice', true, 4, true, 'booze_basket.png'),
('Grill Lovers Pack', 5000, '4 Frozen Hambuger Patties, 4 Hot Dogs, 4 Hamburger Buns, 4 Hot Dog Buns, 1 Set of Tongs', true, 8, false, 'bbq_basket.png'),
('Deluxe Grill Lovers Pack', 12000, '8 Frozen Hambuger Patties, 8 Hot Dogs, 8 Hamburger Buns, 8 Hot Dog Buns, 1 Set of Tongs, 6 Pack of Beer, 6 Pack of Wine Coolers', true, 4, true, 'deluxe_bbq_basket.png');