INSERT INTO products (name, price_cents, description, is_basket, portions, is_deluxe, image, default_quantity) VALUES
('Wine', 2000, 'A fine bottle of wine', false, 1, false, '../assets/product-images/wine.jpg', 1),
('Champagne', 5000, 'A bottle of high-quality champagne', false, 1, false, '../assets/product-images/champagne.jpg', 1),
('Charcuterie Board', 1500, 'Assorted meats and cheeses', false, 1, false, '../assets/product-images/charcuterie.jpg', 1),
('Fruit Plate', 1200, 'Seasonal fresh fruit', false, 1, false, '../assets/product-images/fruit-plate.jpg', 1),
('Turkey Sandwich', 700, 'Tasty fresh turkey sandwich', false, 1, false, '../assets/product-images/turkey-sandwich.jpg', 1),
('Ham Sandwich', 700, 'Tasty fresh ham sandwich', false, 1, false, '../assets/product-imagesham-sandwich.jpg', 1),
('Roast Beef Sandwich', 700, 'Tasty fresh roast beef sandwich', false, 1, false, '../assets/product-images/roast-beef-sandwiche.jpg', 1),
('Veggie Sandwich', 700, 'Tasty fresh roast beef sandwich', false, 1, false, '../assets/product-images/veggie-sandwich.jpg', 1),
('Salty Snacks', 500, 'Assorted salty snacks', false, 1, false, '../assets/product-images/salty-snacks.jpg', 1),
('Sweet Dessert', 1500, 'Decadent sweet treats', false, 1, false, '../assets/product-images/sweet-dessert.jpg', 1),
('Soda Pop', 200, 'A variety of soda flavors', false, 1, false, '../assets/product-images/soda-pop.jpg', 1),
('Chips', 300, 'Bag of potato chips', false, 1, false, '../assets/product-images/chips.jpg', 1),
('Frisbee', 1000, 'Durable frisbee for outdoor fun', false, 1, false, '../assets/product-images/frisbee.jpg', 1),
('Veggie Platter', 1000, 'Fresh cut vegetables with dip', false, 1, false, '../assets/product-images.veggie-platter.jpg', 1),
('Water Bottles', 500, 'Pack of bottled water', false, 1, false, '../assets/product-images/water-bottles.jpg', 1),
('Salad', 800, 'Fresh mixed greens salad', false, 1, false, '../assets/product-images/salad.jpg', 1),
('Branded Quik-A-Nik Blanket', 2500, 'Picnic blanket with branding', false, 1, false, '../assets/product-images/blanket.jpg', 1),
('Branded Quik-A-Nik Cooler', 3000, 'Insulated cooler with branding', false, 1, false, '../assets/product-images/cooler.jpg', 1),
('Paper Plates', 200, 'Pack of disposable paper plates', false, 1, false, '../assets/product-images/paper-plates.jpg', 1),
('Birthday Cake', 3500, 'Delicious birthday cake', false, 1, false, '../assets/product-images/birthday-cake.jpg', 1),
('Birthday Banner', 500, 'Festive birthday banner', false, 1, false, '../assets/product-images/birthday-banner.jpg', 1),
('6 Pack Of Beer', 1200, 'Pack of 6 beer cans', false, 1, false, '../assets/product-images/pack-of-beer.jpg', 1),
('6 Pack Of Coolers', 1200, 'Pack of 6 alcohol coolers', false, 1, false, '../assets/product-images/pack-of-coolers.jpg', 1),
('Bag Of Ice', 300, 'Large bag of ice', false, 1, false, '../assets/product-images/bag-of-ice.jpg', 1),
('Frozen Hamburger Patties', 800, 'Pack of frozen hamburger patties', false, 1, false, '../assets/product-images/hamburger-patties.jpg', 1),
('Hot Dogs', 700, 'Pack of hot dogs', false, 1, false, '../assets/product-images/hotdogs.jpg', 1),
('Hamburger Buns', 200, 'Pack of hamburger buns', false, 1, false, '../assets/product-images/hamburger-buns.jpg', 1),
('Hot Dog Buns', 200, 'Pack of hot dog buns', false, 1, false, '../assets/product-images/hotdog-buns.jpg', 1),
('Tongs', 500, 'Stainless steel tongs', false, 1, false, '../assets/product-images/tongs.jpg', 1),
('Sunscreen', 800, 'Bottle of SPF 30 sunscreen', false, 1, false, '../assets/product-images/sunscreen.jpg', 1),
('Badminton Set', 2000, 'Complete badminton set for outdoor fun', false, 1, false, '../assets/product-images/badminton-set.jpg', 1),
('BBQ Sauce', 300, 'Bottle of BBQ sauce', false, 1, false, '../assets/product-images/bbq-sauce.jpg', 1),
('Ketchup', 200, 'Bottle of ketchup', false, 1, false, '../assets/product-images/ketchup.jpg', 1),
('Mustard', 200, 'Bottle of mustard', false, 1, false, '../assets/product-images/mustard.jpg', 1),
('Relish', 200, 'Jar of relish', false, 1, false, '../assets/product-images/relish.jpg', 1),
('Umbrella', 3000, 'Large, sturdy umbrella', false, 1, false, '../assets/product-images/umbrella.jpg', 1),
('Reusable Water Bottle', 1000, 'Eco-friendly reusable water bottle', false, 1, false, '../assets/product-images/reusable-water-bottle.jpg', 1),
('Tennis Balls', 800, 'Can of 3 tennis balls', false, 1, false, '../assets/product-images/tennis-balls.jpg', 1),
('Collapsable Water Dish', 500, 'Portable water dish for pets', false, 1, false, '../assets/product-images/collapsable-water-dish.jpg', 1),
('Romatic Basket', 7500, '1 Bottle of Champagne, 1 Charcuterie Board, 1 Fruit Platter', true, 2, false, '../assets/product-images/romantic-basket.jpg', 1),
('Family Basket A', 6000, '2 Turkey Sandwiches, 1 Ham Sandwich, 1 Veggie Sandwich, 1 Bag of Chips, 1 Bag of Brownies, 4 Cans of Pop', true, 4, false, '../assets/product-images/basket.jpg', 1),
('Family Basket B', 6000, '2 Ham Sandwiches, 1 Roast Beef Sandwich, 1 Veggie Sandwich, 1 Bag of Pretzels, 1 Bag of Candies, 2 Cans of Pop, 2 Bottles of Water', true, 4, false, '../assets/product-images/basket.jpg', 1),
('Family Basket C', 6000, '2 Veggie Sandwiches, 2 Turkey Sandwiches, 1 Veggie Platter, 1 Fruit Platter, 1 Assorted Trail Mix, 4 Bottles of Water', true, 4, false, '../assets/product-images/basket.jpg', 1),
('Family Basket D', 6000, '2 Roast Beef Sandwiches, 2 Ham Sandwiches, 1 Bag of Chips, 1 Bag of Brownies, 4 Cans of Pop', true, 4, false, '../assets/product-images/basket.jpg', 1),
('Kids Fun Basket', 3000, '1 Bag of Chips, 2 Cans of Pop, 1 Frisbee', true, 2, false, '../assets/product-images/basket.jpg', 1),
('Healthy Quik-A-Nik', 4000, '1 Fruit Platter, 1 Veggie Platter, 4 Water Bottles, 1 Large Garden Salad', true, 2, false, '../assets/product-images/basket.jpg', 1),
('Deluxe Quik-A-Nik Starter Kit', 10000, '1 Branded Quik-A-Nik Blanket, 1 Branded Quik-A-Nik Cooler, Family Basket A', true, 4, true, '../assets/product-images/basket.jpg', 1),
('Celebration Extravaganza', 10000, '15 Assorted Sandwiches, 1 Birthday Cake, 1 Birthday Banner, 1 Package of Paper Plates', true, 15, true, '../assets/product-images/basket.jpg', 1),
('Adult Hydration Basket', 4000, '6 Pack of Beer, 6 Pack of Wine Coolers, 1 Bag of Ice', true, 4, true, '../assets/product-images/basket.jpg', 1),
('Grill Lovers Pack', 5000, '4 Frozen Hambuger Patties, 4 Hot Dogs, 4 Hamburger Buns, 4 Hot Dog Buns, 1 Set of Tongs', true, 8, false, '../assets/product-images/grill-lovers.jpg', 1),
('Deluxe Grill Lovers Pack', 12000, '8 Frozen Hambuger Patties, 8 Hot Dogs, 8 Hamburger Buns, 8 Hot Dog Buns, 1 Set of Tongs, 6 Pack of Beer, 6 Pack of Wine Coolers', true, 16, true, '../assets/product-images/grill-lovers.jpg', 1);